# import time
# f1=open("ihub3.txt","r")
# obj1=f1.read()
# print("File name is :",f1.name)
# print('---------')
# print(obj1)
# print('--------')
# print()
# f1.close()
# print()
# time.sleep(2)
# print('end of an application')

import time
f1=open("ihub3.txt","r")
obj1=f1.read(2)
print("File name is :",f1.name)
print('---------')
print(obj1)
print('--------')
print()
f1.close()
print()
time.sleep(2)
print('end of an application')
